version: "3"
services:
    cassandra-node:
        container_name: cassandra-node
        image: himanshu17/mycassandra:latest
        ports:
            - "9042:9042"
            - "7000:7000"
        environment: 
            - CASSANDRA_CLUSTER_NAME='SaveAllWebCluster'
            - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
            - CASSANDRA_RPC_ADDRESS=127.0.0.1
            - CASSANDRA_SEEDS="127.0.0.1"
            - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_AUTO_BOOTSTRAP=false
