version: "3"
services:
    cassandra-node:
        container_name: cassandra-node
        image: himanshu17/mycassandra:latest
        environment: 
            - CASSANDRA_BROADCAST_ADDRESS=127.0.0.1
        ports:
            - "9042:9042"
            - "7000:7000"
